name: Test Automation Workflow

on:
  schedule:
    - cron: "00 18 * * *"
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      # Fix: Add settings-security.xml if using encrypted Maven server passwords
      - name: Set up Maven security files
        run: |
          mkdir -p ~/.m2
          if [ ! -z "${{ secrets.SETTINGS_SECURITY }}" ]; then
            echo "${{ secrets.SETTINGS_SECURITY }}" > ~/.m2/settings-security.xml
          fi
          if [ ! -z "${{ secrets.SETTINGS_XML }}" ]; then
            echo "${{ secrets.SETTINGS_XML }}" > ~/.m2/settings.xml
          fi

      # Fix: Use a unique Chrome user data dir for Selenium runs
      - name: Set unique Chrome user data dir
        id: chrome_user_data
        run: echo "CHROME_USER_DATA_DIR=$(mktemp -d)" >> $GITHUB_ENV

      # Run Maven tests (your test code should read CHROME_USER_DATA_DIR for --user-data-dir)
      - name: Running Test Automation Framework with Maven
        run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=false

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test Logs
          path: logs/

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Test Reports
          path: reportAll.html

      - name: Test Execution Status
        run: echo "Test Execution Completed"
